### ISSUE TITLE
Expand preloader.php file header to better explain the file is auto-generated

### ISSUE THREAD

**Issue by jamisonbryant** [cnizzardini/cakephp-preloader#21]
I like that `preload.php` has a generated-at line at the top of the file:

```
# Preload Generated at 8/20/24, 9:02 PM 
```

I was wondering if it would be possible to expand this message to something like the following?

```
# ------------------------------------------------------------------------
# AUTO-GENERATED FILE: DO NOT MODIFY DIRECTLY
# ------------------------------------------------------------------------
# This PHP script was automatically generated. Any manual modifications 
# made to this file may be overwritten the next time the script is generated.
#
# If you need to make changes, please update the source template or the 
# generator script that produces this file, rather than editing this file 
# directly.
#
# Last Generated: [Timestamp]
# ------------------------------------------------------------------------
```

Technically I think we _could_ do this by hooking into the `beforeWrite` event but it seems like a change that everyone that uses the plugin could benefit from, rather than just us.

**Comment by cnizzardini** [comment]
I don't see a huge value in this as this file exists on production only and I'd hope someone with prod access knows this. I'll accept a PR though.

**Comment by jamisonbryant** [comment]
Fair enough. Thanks for the feedback.
